"""Public model-guided repository discovery API."""

from contextforge.discovery.completeness import review_completeness
from contextforge.discovery.models import (
    DISCOVERY_SCHEMA_VERSION,
    CompletenessWarning,
    DiscoveryAction,
    DiscoveryActionBatch,
    DiscoveryBudget,
    DiscoveryBudgetUsage,
    DiscoveryCandidate,
    DiscoveryCandidateRecord,
    DiscoveryLineRange,
    DiscoveryMode,
    DiscoveryObservation,
    DiscoveryRequest,
    DiscoveryRunRecord,
    DiscoveryState,
    FinalContextSelection,
    IndexedContextSelection,
    SelectionReason,
)
from contextforge.discovery.renderers import (
    DiscoveryRenderError,
    DiscoveryResultFormat,
    render_context_suggestion,
)
from contextforge.discovery.session import (
    DISCOVERY_SYSTEM_INSTRUCTIONS,
    DiscoveryCancelledError,
    DiscoveryError,
    DiscoveryLimitError,
    DiscoveryProtocolError,
    DiscoverySession,
    DiscoverySourceChangedError,
    DiscoveryUnavailableError,
    discover_repository,
)
from contextforge.discovery.tools import (
    DISCOVERY_TOOL_SCHEMAS,
    TOOL_INPUT_MODELS,
    DiscoveryKnowledge,
    DiscoveryToolExecutor,
    GitDiffProvider,
    GitDiffResult,
    ToolBudgetExceededError,
    ToolBudgetTracker,
)

__all__ = [
    "DISCOVERY_SCHEMA_VERSION",
    "DISCOVERY_SYSTEM_INSTRUCTIONS",
    "DISCOVERY_TOOL_SCHEMAS",
    "TOOL_INPUT_MODELS",
    "CompletenessWarning",
    "DiscoveryAction",
    "DiscoveryActionBatch",
    "DiscoveryBudget",
    "DiscoveryBudgetUsage",
    "DiscoveryCancelledError",
    "DiscoveryCandidate",
    "DiscoveryCandidateRecord",
    "DiscoveryError",
    "DiscoveryKnowledge",
    "DiscoveryLimitError",
    "DiscoveryLineRange",
    "DiscoveryMode",
    "DiscoveryObservation",
    "DiscoveryProtocolError",
    "DiscoveryRenderError",
    "DiscoveryRequest",
    "DiscoveryResultFormat",
    "DiscoveryRunRecord",
    "DiscoverySession",
    "DiscoverySourceChangedError",
    "DiscoveryState",
    "DiscoveryToolExecutor",
    "DiscoveryUnavailableError",
    "FinalContextSelection",
    "IndexedContextSelection",
    "GitDiffProvider",
    "GitDiffResult",
    "SelectionReason",
    "ToolBudgetExceededError",
    "ToolBudgetTracker",
    "discover_repository",
    "review_completeness",
    "render_context_suggestion",
]
